// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjUZGH4gTmgxcgv2SOV9oE8Cqv3EB_gk',
    appId: '1:606810231575:web:1dc37ddae428edf9bb1d52',
    messagingSenderId: '606810231575',
    projectId: 'dicoding-restaurant-app-f24e2',
    authDomain: 'dicoding-restaurant-app-f24e2.firebaseapp.com',
    storageBucket: 'dicoding-restaurant-app-f24e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKMxvkZUL3JwxEbBTSqTrj9-JuX6G78o',
    appId: '1:606810231575:android:e62c83dca8976697bb1d52',
    messagingSenderId: '606810231575',
    projectId: 'dicoding-restaurant-app-f24e2',
    storageBucket: 'dicoding-restaurant-app-f24e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkM73C_IVMqX3RWLER7Si-fqKK54PO3iA',
    appId: '1:606810231575:ios:541966b2bb2007d3bb1d52',
    messagingSenderId: '606810231575',
    projectId: 'dicoding-restaurant-app-f24e2',
    storageBucket: 'dicoding-restaurant-app-f24e2.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkM73C_IVMqX3RWLER7Si-fqKK54PO3iA',
    appId: '1:606810231575:ios:541966b2bb2007d3bb1d52',
    messagingSenderId: '606810231575',
    projectId: 'dicoding-restaurant-app-f24e2',
    storageBucket: 'dicoding-restaurant-app-f24e2.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVjUZGH4gTmgxcgv2SOV9oE8Cqv3EB_gk',
    appId: '1:606810231575:web:2c1915425e52085dbb1d52',
    messagingSenderId: '606810231575',
    projectId: 'dicoding-restaurant-app-f24e2',
    authDomain: 'dicoding-restaurant-app-f24e2.firebaseapp.com',
    storageBucket: 'dicoding-restaurant-app-f24e2.firebasestorage.app',
  );
}
